# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'openCV' do
platform :ios, "9.0"
pod 'OpenCV'
end

target 'openCVTests' do

end

target 'openCVUITests' do

end

